### ISSUE TITLE
Throws UnsatisfiedLinkError (clojure)

### ISSUE THREAD

**Issue by madstap** [naomijub/brcode#25]
I tried to follow the install instructions, but I can't get the library to work.

I expected [this to work](/madstap/stunning-octo-chainsaw/commit/12999ba4a0be1cd8f82ec606a86435397f1fdf50) (on ubuntu).

(Ie. adding `libbrcode.so` to the root of the project)

```
brcode-repro$ lein test

lein test brcode-repro.core-test

lein test :only brcode-repro.core-test/br-code-test

ERROR in (br-code-test) (NativeLibrary.java:93)
expected: (some? (pix/brcode->edn code))
  actual: java.lang.UnsatisfiedLinkError: libbrcode.so: cannot open shared object file: No such file or directory
 at jnr.ffi.provider.jffi.NativeLibrary.loadNativeLibraries (NativeLibrary.java:93)
    jnr.ffi.provider.jffi.NativeLibrary.getNativeLibraries (NativeLibrary.java:71)
    ... <more stacktrace>
```

I also tried putting the .so file in `src`, so it would be on the classpath, but it behaves the same.

**Comment by naomijub** [comment]
Do you have this flag `export LD_LIBRARY_PATH=.`?

if yes, can you try this [build from source](https://github.com/naomijub/brcode/blob/master/README.md#build-from-source) and put the `.so` in the root of your project?

**Comment by madstap** [comment]
Setting `export LD_LIBRARY_PATH=.` worked, thanks!
