### ISSUE TITLE
BACEN atualizou a documentação

### ISSUE THREAD

**Issue by naomijub** [naomijub/brcode#26]
https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/Anexo%20I%20-%20QRCodes%20-%20Especifica%C3%A7%C3%A3o%20-%20vers%C3%A3o%201-1.pdf
https://www.bcb.gov.br/content/estabilidadefinanceira/spb_docs/ManualBRCode.pdf

**Comment by naomijub** [comment]
Esperando o Bacen dizer que ta na versão final mesmo...

**Comment by naomijub** [comment]
Mais um https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/II-ManualdePadroesparaIniciacaodoPix-versao2-1.pdf

**Comment by ninrod** [comment]
@naomijub, a estrutura do QR (tanto estático, quanto dinâmico) não foi atualizada. continua estável. As versões continuarão a serem liberadas conforme novas features vão sendo incorporadas ao arranjo. Ano que vem provavelmente teremos QR do Pagador, por exemplo.

**Comment by naomijub** [comment]
@ninrod Obrigada

**Comment by ninrod** [comment]
> @ninrod Obrigada

Disponha. Aliás, parabéns pelo repositório. Clojure, Dart, Rust e Elixir: uma bela seleção de linguagens.
